language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - export CODACY_PROJECT_TOKEN=377ae5e9d3bb458f9cc892443a83f26a
  - coverage run -m unittest discover -s ./tests && coverage xml && python-codacy-coverage -r coverage.xml